---
Name: yes_no_any_filter
---

SilverStripe\ORM\FieldType\DBBoolean:
  extensions:
    - Sunnysideup\YesNoAnyFilter\DBBooleanColourfull


SilverStripe\ORM\DataObject:
  extensions:
    - Sunnysideup\YesNoAnyFilter\FixBooleanSearchAsExtension
